# Day 1: Playing with NumPy

## Melakukan Import dataset

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Deklasi Array di numpy

In [43]:
#Bentuk Array Biasa
a = np.array([1, 2, 3, 4, 5])
print(a)

# Dalam bentuk matriks
b = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ])
print(b)
print(b.shape)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [15]:
c = np.arange(100)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [12]:
c = np.arange(12).reshape(4, 3)
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [54]:
#Membuat matriks ones
a = np.ones((2,3))
print(a)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [63]:
#Membuat matriks dengan elemen random
a = np.random.random((2,3))
print(a * 10)

[[ 7.01521339  8.35232688  7.12409075]
 [ 7.10174226  4.51529595  5.2554226 ]]


## Operasi yang bisa dilakukan di NumPy Array

In [18]:
a = np.array([10, 20, 30, 40, 50])
b = np.arange(5)

#Penjumlahan
print(a + b)
#Pengurangan
print(a - b)
#Eksponen
print(b ** 3)
#Logical Operators
print(a >= 30)

#Melakukan query dengan logical operators
print( a[a >= 30] )

[10 21 32 43 54]
[10 19 28 37 46]
[ 0  1  8 27 64]
[False False  True  True  True]
[30 40 50]


## Manipulasi dan Operasi Matrix di NumPy

In [64]:
#Cara buat matriks (manual)
a = np.arange(9)
print(a)
a = a.reshape(3, 3)
print(a)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [65]:
#Cara buat matriks (auto)
b = np.array([
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
    ])

In [46]:
#Penjumlahan matriks
print(a + b)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


In [47]:
#Perkalian dengan elemen pada baris dan kolom yang sama
print(a * b)

[[ 0  1  2]
 [ 6  8 10]
 [18 21 24]]


In [48]:
#Perkalian dot product
print(a.dot(b))

[[ 8  8  8]
 [26 26 26]
 [44 44 44]]


In [59]:
#Melakukan Penjumlahan Kumulatif
print(a.cumsum(axis = 1))

[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]]


In [49]:
#Bisa menggunakan operator ini juga
a -= 2
b += 3

print(a)
print(b)

[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]
[[4 4 4]
 [5 5 5]
 [6 6 6]]


In [66]:
#Melihat keunikan elemen matriks
print(a.sum())
print(a.min())
print(a.max())

36
0
8


In [71]:
#Kalau mau spesifik per baris atau per kolom
#axis = 0 itu buat kolom dan axis = 1 itu buat baris
print(a.sum(axis = 0))
print(a.min(axis = 1))
print(a.max(axis = 1))

[ 9 12 15]
[0 3 6]
[2 5 8]


## Melihat ciri2 matriks

In [52]:
a = np.arange(12).reshape(3, 4)

#Bentuk matriks sebelum transpos
print(a)
#Cari tahu bentuk matriks
print(a.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [53]:
#Setelah transpos
print(a.T)
#Shapenya
print(a.T.shape)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
(4, 3)
